### ISSUE TITLE
Crash on startup (forge v43.2.4 [1.19.2])

### ISSUE THREAD

**Issue by OxiiGiin1** [ThreeTAG/PalladiumCore#1]
[https://pastebin.com/23peWyW5](url)

**Comment by Lucraft** [comment]
can you send the actual crash report

**Comment by OxiiGiin1** [comment]
[crash-2023-04-05_05.34.02-fml.txt](https://github.com/ThreeTAG/PalladiumCore/files/11163184/crash-2023-04-05_05.34.02-fml.txt)

**Comment by OxiiGiin1** [comment]
bump?

**Comment by ForgottenUmbrella** [comment]
It isn't polite to bump threads, because it adds noise to developers' notifications and makes it harder to sift through useful notifications.

That aside, from what I understand, one reason that your game is crashing with a `ConcurrentModificationException` is because you have the Gliders mod installed on Forge, which depends on PalladiumCore.

[The Gliders mod is registering a lambda to run on Palladium's `CLIENT_SETUP` event](https://github.com/VentureCraftMods/MC-Gliders/blob/bdf0ff48b67d3e009b52d5fefbbc7d468cb6a28a/common/src/main/java/net/venturecraft/gliders/VCGlidersClient.java#L27), and that lambda is calling `ItemProperties::register`, which is not a thread-safe function. One way that Forge differs from Fabric is that it runs client setup for multiple mods in parallel, which can lead to multiple mods simultaneously calling `ItemProperties::register`, which in turn can cause the crash (or not, because multithreading is funny like that).

I don't understand the codebase fully, but I *think* changing [this line](https://github.com/ThreeTAG/PalladiumCore/blob/8d9d51f86cec4f98f41d7f4813cc571256f8c870/forge/src/main/java/net/threetag/palladiumcore/forge/PalladiumCoreForge.java#LL47C54-L47C54) to `event.enqueueWork(() -> LifecycleEvents.CLIENT_SETUP.invoker().run());` should fix it, once the Gliders mod updates to use a version of PalladiumCore that contains this fix. I'll send in a PR in few minutes.
